spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/team_b
    username: team_b
    password: green502

# mybatis config
mybatis:
  type-aliases-package: com.green.booktodolist
  mapper-locations: mapper/**/*.xml

# swagger
springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: D:/download/todo/

server:
  port: 8081

# 알라딘 api
aladin:
  clientTTBKey: ttb3720451526001