spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 12MB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.144:3306/team_b
    username: team_b
    password: green502

# mybatis config
mybatis:
  type-aliases-package: com.green.booktodolist
  mapper-locations: mapper/**/*.xml

# swagger
springdoc:
  swagger-ui:
    path: /swagger.html

file:
  dir: D:/download/todo/

server:
  port: 8081

# 알라딘 api
aladin:
  clientTTBKey: ttb3720451526001

# 국립중앙도서관 api
isbnbook:
  API_KEY: e7e239ae4128719a998e3a31ab3041b1a2cc0b014e95d5f4f2914e3187bbdc29